CREATE TABLE IF NOT EXISTS published_payloads (
  resource_uid VARCHAR(128) PRIMARY KEY,
  payload_json JSON NOT NULL,
  version_no BIGINT NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
