apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-control-plane.fullname" . }}-grafana-provisioning
  namespace: {{ include "grafana-control-plane.namespace" . }}
data:
  control-plane-app.yaml: |
    apiVersion: 1

    apps:
      - type: {{ .Values.grafana.pluginId }}
        org_id: 1
        disabled: false
