apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-control-plane.fullname" . }}-mysql
  namespace: {{ include "grafana-control-plane.namespace" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "grafana-control-plane.fullname" . }}-mysql
  ports:
    - port: {{ .Values.mysql.servicePort }}
      targetPort: {{ .Values.mysql.servicePort }}
      protocol: TCP
      name: mysql
