apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-control-plane.fullname" . }}-platform-api
  namespace: {{ include "grafana-control-plane.namespace" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "grafana-control-plane.fullname" . }}-platform-api
  ports:
    - port: {{ .Values.platformApi.servicePort }}
      targetPort: {{ .Values.platformApi.servicePort }}
      protocol: TCP
      name: http
